name: Test
on: push
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install deps backend
              working-directory: ./app
              run: yarn
            - name: Check types backend
              run: yarn typecheck

            - name: Install deps mobile
              working-directory: ./mobile
              run: yarn
            - name: Copy initialize files
              run: cp mobile/src/services/initialise.local.ts mobile/src/services/initialise.ts
            - name: Check types mobile
              run: yarn typecheck
            - name: Run tests
              run: yarn test

            - name: Run backend
              working-directory: ./
              run: docker-compose -f docker-compose.yaml up --build -d
            - name: Show logs
              if: ${{ failure() }}
              run: docker-compose logs
